/*
Modifications to enable ACE Constrained RS

Copyright 2018 Carnegie Mellon University. All Rights Reserved.

Cn-cbor Copyright 2015 Carsten Bormann.

NO WARRANTY. THIS CARNEGIE MELLON UNIVERSITY AND SOFTWARE ENGINEERING INSTITUTE MATERIAL IS FURNISHED ON AN "AS-IS" BASIS. CARNEGIE MELLON UNIVERSITY MAKES NO WARRANTIES OF ANY KIND, EITHER EXPRESSED OR IMPLIED, AS TO ANY MATTER INCLUDING, BUT NOT LIMITED TO, WARRANTY OF FITNESS FOR PURPOSE OR MERCHANTABILITY, EXCLUSIVITY, OR RESULTS OBTAINED FROM USE OF THE MATERIAL. CARNEGIE MELLON UNIVERSITY DOES NOT MAKE ANY WARRANTY OF ANY KIND WITH RESPECT TO FREEDOM FROM PATENT, TRADEMARK, OR COPYRIGHT INFRINGEMENT.

Released under a MIT-style license, please see https://github.com/cabo/cn-cbor/blob/master/LICENSE or contact permission@sei.cmu.edu for full terms.

[DISTRIBUTION STATEMENT A] This material has been approved for public release and unlimited distribution.  Please see Copyright notice for non-US Government use and distribution.

DM18-1273
*/
const char *cn_cbor_error_str[] = {
 "CN_CBOR_NO_ERROR",
 "CN_CBOR_ERR_OUT_OF_DATA",
 "CN_CBOR_ERR_NOT_ALL_DATA_CONSUMED",
 "CN_CBOR_ERR_ODD_SIZE_INDEF_MAP",
 "CN_CBOR_ERR_BREAK_OUTSIDE_INDEF",
 "CN_CBOR_ERR_MT_UNDEF_FOR_INDEF",
 "CN_CBOR_ERR_RESERVED_AI",
 "CN_CBOR_ERR_WRONG_NESTING_IN_INDEF_STRING",
 "CN_CBOR_ERR_INVALID_PARAMETER",
 "CN_CBOR_ERR_OUT_OF_MEMORY",
 "CN_CBOR_ERR_FLOAT_NOT_SUPPORTED"
};
