make WITH_WEBSERVER=0 WITH_WEBSERVER_LITE=0 WITH_UDPSERVER=0 WITH_UDPCLIENT=0 WITH_NODE_CONFIG=0 WITH_NODE_INFO=0 \
WITH_NVM_PROXY=0 WITH_DNS_PROXY=0 WITH_DTLSECHO=0 \
WITH_LLSEC=1 WITH_IP64=1 \
WITH_TINYDTLS=1 WITH_COAPSERVER=1 all
